"""Shared CLI utilities and base module for Dotman."""

from dotman.cli.commands import (
    absorb_changes,
    add_repository,
    clone,
    deploy,
    history,
    init,
    list_packages,
    list_repositories,
    pull,
    push,
    remove_repository,
    rollback,
    set_default_repository,
    show_repository,
    status,
    undeploy,
    watch,
)
from dotman.cli_utils import (
    app,
    console,
    get_config,
    get_repository_option,
    repo_app,
)

__all__ = [
    "absorb_changes",
    "add_repository",
    "app",
    "console",
    "get_config",
    "get_repository_option",
    "repo_app",
    "init",
    "clone",
    "push",
    "pull",
    "deploy",
    "undeploy",
    "status",
    "list_packages",
    "history",
    "rollback",
    "watch",
    "list_repositories",
    "remove_repository",
    "set_default_repository",
    "show_repository",
]
